version: "3"

services:
  marcal_project_database:
    env_file:
      - .env
    image: dpage/pgadmin4
    ports:
      - "${POSTGRES_PORTS}"
    container_name: "marcal_project_database"
    restart: always
    volumes: 
      - ./marcal_project_database:/var/lib/postgresql/data
    environment:
      PGADMIN_SERVER_NAME: NomeDoProjeto
      PGADMIN_IP: 177.136.201.182
      PGADMIN_PORT: 5439
      PGADMIN_MAINTENANCE_DB: temp
      PGADMIN_USERNAME: aluno_20201214010008
      PGADMIN_PASSWORD: 111315
volumes: 
  marcal_project_database:
